version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app/src/frontend
      - ./src/shared:/app/src/shared
      - /app/src/frontend/node_modules
      - /app/src/shared/node_modules
    environment:
      - NODE_ENV=development
      - VITE_WEBSOCKET_URL=ws://localhost:4001
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001" # WebSocket port
    volumes:
      - ./src/backend:/app/src/backend
      - ./src/shared:/app/src/shared
      - /app/src/backend/node_modules
      - /app/src/shared/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - WS_PORT=4001
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
